### ISSUE TITLE
Add a table of contents

### ISSUE THREAD

**Issue by kinow** [veeral-patel/learn-security-engineering#2]
That would help with navigation. There are a few tools that generate that for markdown files.

**Comment by veeral-patel** [comment]
@kinow good idea! do you know how we'd keep the TOC up to date, though, without manually updating it all the time?

**Comment by kinow** [comment]
> @kinow good idea! do you know how we'd keep the TOC up to date, though, without manually updating it all the time?

Unfortunately the only ones I've seen so far require users to update the TOC if they change something in a pull request or commit.

There are actions/scripts that can be used to automate that, but it relies on maintaining some syntax in the file (e.g. a token that is replaced by the TOC), and are a bit more complex. Most of the "-awesome" lists keep their TOC manually I think, e.g. https://raw.githubusercontent.com/vuejs/awesome-vue/master/README.md

**Comment by veeral-patel** [comment]
done!
