### ISSUE TITLE
compliance and security in had of a humming bird

### ISSUE THREAD

**Issue by dennis-ops** [veeral-patel/learn-security-engineering#4]
you can't catch up. you can't fly and if you catch a humming bird the long beak will break security when he pecks you hand. this is my answer to compliance and security. in today world every thing that effects you. why does it take so much pain to try to be who you are when they ask you every single day the same question when the answer is known and they will not tell you so next spin is back again and now one will try an be the correct help.

**Comment by veeral-patel** [comment]
@dennis-ops sorry I don't follow...is there an improvement I can make to the repo for you?

**Comment by cboley4204** [comment]
You was absolutely right
